spring.application.name=scorm
spring.datasource.url=jdbc:mysql://localhost:3306/scrom_db?createDatabaseIfNotExist=true
spring.datasource.username=****
spring.datasource.password=****
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

scorm.storage-path=C:/scorm-storage
